### ISSUE TITLE
misc "getting started" issues

### ISSUE THREAD

**Issue by bdarcus** [Lambda-Emacs/lambda-emacs#2]
I just tried to install this on a VM, to test the citar-capf, but ran into a few issues.

First, in general, the doc could use a quick "what to do" instructions to get up in running. I assume that would just be a git clone, and then to add a `lambda-user/config.el` file? Except I'm not figuring this out, as my `config.el` isn't getting loaded.

Second, you have an odd (from my Linux POV) `lem-local-bin `dir variable, where emacs will throw an error if that dir isn't present.

Finally, I get an error with one of the package defs.

```terminal
No ':repo' specified for package 'lambda-line'
```

Otherwise, this looks great! When I get a chance, I'll add a link to it on the citar README.

PS - given the gorgeous UI, you should add a screenshot ;-)

**Comment by bdarcus** [comment]
Now getting `unable to find theme file` warnings.

**Comment by mclearc** [comment]
yep -- sorry that was hardcoded to a path on my system. Should be fixed now

**Comment by mclearc** [comment]
thanks again for all this feedback -- super helpful! Yes, I definitely need to make the initial startup process more robust and error proof. Part of the problem is that I ended up taking some of the config files out since they seemed too tailored to my workflow. I'm also in the process of trying to make my [consult-notes](https://github.com/mclear-tools/consult-notes) package more robust. When I do I'll add that to the notes module. In the meantime I've just commented out the missing modules from lem-library-dir.

**Comment by bdarcus** [comment]
I gave it another go, and installation never completed on:

1. GUIX VM (Emacs 28.1)
2. GUIX VM (Emac Next/29)
3. my Fedora laptop install, using `which-emacs.sh`.

For the first two, Emacs crashes before completing.

Foe 3, it _seems_ to get through, but a lot of packages aren't installed.

:shrug:

Also, this isn't you, but there are tons of compliler warnings because some packages violate some convention or something. You may want to silence those.

**Comment by mclearc** [comment]
Thanks for trying this again. Hope I can take a closer look at how this is working (or not working) later this weekend

**Comment by bdarcus** [comment]
Sure thing; no rush. Just thought you should know.

I'll update if I figure anything out.

**Comment by mclearc** [comment]
If you happen to have time, it might be worth pulling the recent changes and giving things another try. I've updated the readme with a brief bit of advice on how to get started (this needs improvement to be sure), and I've created the option to generate a user config file. On my end things download without errors.

**Comment by bdarcus** [comment]
The weird thing is, I get no errors either. But things aren't setup correctly.

For example:

1. initially vertico is not activated; I have to manually activate
2. citar commands are not available

If I look in the config file, I see the citation module is not specified by default, so add that and restart. But still no citar, etc.

Do I need to do something to get the new packages from that module to install? In doom, which also uses straight behind the scenes, I'd do `doom sync`.

PS - actually, I do get this error:

```elisp
[yas] Check your `yas-snippet-dirs': /home/bruce/Code/lambda-emacs/.local/temp/etc/all-snippets/yasnippet-snippets is not a directory
[yas] Check your `yas-snippet-dirs': /home/bruce/Code/lambda-emacs/.local/temp/etc/all-snippets/yasnippet-snippets/ is not a directory
[yas] Check your `yas-snippet-dirs': /home/bruce/Code/lambda-emacs/.local/temp/etc/all-snippets/lem-snippets/ is not a directory
yas--subdirs: Opening directory: No such file or directory, /home/bruce/Code/lambda-emacs/.local/temp/etc/all-snippets/yasnippet-snippets
```

**Comment by bdarcus** [comment]
BTW, one little helpful thing Doom does in it's init file is include all (or most) of it's modules, but comment out optional ones. You might consider that?

**Comment by mclearc** [comment]
> BTW, one little helpful thing Doom does in it's init file is include all (or most) of it's modules, but comment out optional ones. You might consider that?

Yeah -- the default startup (if you choose not to create a user config file) will load pretty much all the modules that there currently are. The user config file just loads a subset of them. But once I figure out a more graceful way to make a config file I'll do as you suggest. 

As for the error -- I've pushed a change to the yasnippet setup that hopefully avoids any problems in case dirs don't exist. I've also added the writing and citation modules to the default config that gets created. I wonder if there are some other issues that are coming up since I'm working on macos and you on linux though. It depends I guess on whether things start to work for you with these changes :)

**Comment by bdarcus** [comment]
> As for the error -- I've pushed a change to the yasnippet setup that hopefully avoids any problems in case dirs don't exist. 

That does solve that issue. But the other issues remain.

> I wonder if there are some other issues that are coming up since I'm working on macos and you on linux though.

I was wondering that too, though messages does show an embark-related issue:

```elisp
Configuring package vertico-buffer...done (0.000s)
Loading package vertico-buffer...done (0.007s)
funcall-interactively: Text is read-only
Configuring package embark...done (0.000s)
completing-read-default: Autoloading file /home/bruce/Code/lambda-emacs/.local/lambda-library/straight/build/embark/embark.elc failed to define function embark-occur-toggle-view
funcall-interactively: Text is read-only
exchange-point-and-mark: No mark set in this buffer
Configuring package embark...done (0.000s)
completing-read-default: Autoloading file /home/bruce/Code/lambda-emacs/.local/lambda-library/straight/build/embark/embark.elc failed to define function embark-occur-toggle-view
Configuring package embark...done (0.000s)
completing-read-default: Autoloading file /home/bruce/Code/lambda-emacs/.local/lambda-library/straight/build/embark/embark.elc failed to define function embark-occur-toggle-view
```

Hmm .... those are elc files, while I'm using nativecomp. I wonder if there's something there?

Except I do end up with an `eln-cache` directory, so now I'm just confused.

What version of Emacs are you using?

At some point you probably should test on Linux, say via a VM.

**Comment by mclearc** [comment]
> What version of Emacs are you using?

Emacs 29 (I build from the main branch). I have no idea why embark would be throwing that error. perhaps try simply commenting that out in the bindings and see if that works? If so maybe I'll leave the bindings blank so as to simplify things.

**Comment by bdarcus** [comment]
I'm wiped the straight directory and am redoing it all fresh.

**Comment by bdarcus** [comment]
Compiling now.

On an only vaguely-related note, it seems you use org-roam? Or maybe not, and hence consult-notes.

But if you have any feedback on this in progress PR ...

https://github.com/bdarcus/citar/pull/603

**Comment by bdarcus** [comment]
> I wiped the straight directory and am redoing it all fresh.

I did remove the embark line, but alas, I see no difference, and can't see any obvious error. Very weird.

I do think it would be good to indicate progress on compilation somehow; at least while in progress, and when done.

**Comment by bdarcus** [comment]
BTW, are you aware of zk? It's developed by a citar contributor, and seems very vaguely similar (at least in using grep, consult, citar, embark!) to consult-notes?

https://github.com/localauthor/zk

Though that's a pretty strict interpretation of a zettelkasten approach to notes, I understand (I haven't tried though).

**Comment by bdarcus** [comment]
I just took a look in the straight repos dir, and neither citar nor citar-capf were there.

So I deleted the directory again, and the config file (to which I had added `lem-setup-citation`, restarted, and again, here's the list of repos:

```console
ace-window/                emacs-hide-mode-line/     org/
all-the-icons-completion/  emacsmirror-mirror/       outline-minor-faces/
all-the-icons-dired/       emacs-revert-buffer-all/  packed/
all-the-icons.el/          emacs-which-key/          parent-mode/
auto-compile/              emacs-winum/              popper/
avy/                       embark/                   project/
backup-walker/             expand-region.el/         pulsing-cursor/
cape/                      f.el/                     rainbow-mode/
col-highlight/             font-lock-plus/           restart-emacs/
company-mode/              gnu-elpa-mirror/          s.el/
company-org-block/         goggles/                  straight.el/
compat/                    helpful/                  svg-lib/
consult/                   highlight-numbers/        svg-tag-mode/
consult-dir/               hl-line-plus/             transient/
corfu/                     hl-todo/                  use-package/
corfu-doc/                 hydra/                    vertico/
crosshairs/                ibuffer-vc/               visual-regexp.el/
crux/                      info-colors/              vline/
dash.el/                   kind-icon/                ws-butler/
dimmer.el/                 lambda-line/              xref/
el-get/                    lambda-themes/            xwwp/
elisp-demos/               marginalia/               yasnippet/
elisp-refs/                melpa/                    yasnippet-snippets/
el-patch/                  ns-auto-titlebar/
emacs-async/               orderless/

```

**Comment by mclearc** [comment]
Yeah -- that is very strange as it downloads all the relevant packages for me on a clean install (on MacOS). So I may really need to figure out spinning up a VM to do this on a linux machine.

**Comment by mclearc** [comment]
Just in case you're still interested in trying to get lambda-emacs up and running, I tested it today on a VM with Ubuntu-20.04.2 and emacs 28 (via snap). Aside from a few path issues that assumed macos (which I've hopefully now fixed) it seems like everything works as expected (though I haven't done extensive testing...). All packages download and no errors or other issues that I can see at startup. So I'm not entirely sure why you're seeing the problems that you are.

**Comment by bdarcus** [comment]
I'm totally out of ideas.

I just again did a `git pull`, wiped the straight dir, reopened emacs (using `with-emacs.sh`), and said "no" when prompted.

Again citar and citar-capf did not install, and there were no error messages.

Also again, vertico is not active initially.

Actually, I do see this a "void symbol" message for `active-theme`. But I doubt that's the issue.

**Comment by mclearc** [comment]
If you say "yes" at the config prompt do things go any better?

**Comment by mclearc** [comment]
Just tried it without any config setting and didn't have any problems. Very odd. 

<img width="1624" alt="Screen Shot 2022-05-26 at 16 53 18" src="https://user-images.githubusercontent.com/1502422/170578356-2183e9f1-f43e-4310-96eb-2abc52b4b252.png">

**Comment by bdarcus** [comment]
> If you say "yes" at the config prompt do things go any better?

Nope.

When I do `M-x`, I do see this, which hints at vertico:

```
Loading package vertico-buffer...
```

But it doesn't actually activate, and I have to do `M-x vertico-mode`. THEN that works.

**Comment by bdarcus** [comment]
FYI, @mclearc, I just tested this again on my guix VM, and it finally installed correctly!

I'll close this.

**Comment by bdarcus** [comment]
I do get a void symbol error with citar though: `all-the-icons-icticon`.

**Comment by mclearc** [comment]
> I do get a void symbol error with citar though: `all-the-icons-icticon`.

Hmm - that may be because of either the load order or the need to download all the icons first. I'll take a look. Thanks again for persisting in trying the config out!
